# Quantifying Growth variability

In [21]:
import pandas as pd
import geopandas as gpd
import numpy as np
import folium
from ipywidgets import interact, widgets
from IPython.display import display
import branca.colormap as cm
from shapely import wkt

In [35]:
#import data
df = pd.read_csv(r'c:\Users\ici-1\Desktop\NADJA\Verrio\almond_water_use_data\output\basis_for_growth_stability.csv')

In [36]:
df.columns

Index(['Unnamed: 0.1', 'OBJECTID', 'CUL_CAMPAN', 'CUL_ID_x', 'OSA_ID',
       'Shape_Leng', 'Shape_Area', 'layer', 'path', 'geometry', 'Unnamed: 0',
       'CUL_ID_y', 'year', 'auc', 'gdd', 'ndvi', 'doy', 'percentile', 'status',
       'pct_diff_from_P80_avg', 'pct_diff_from_P95_avg'],
      dtype='object')

In [37]:
df['geometry'] = df['geometry'].apply(wkt.loads)
df = gpd.GeoDataFrame(df, geometry='geometry')
df.set_crs("EPSG:4326", inplace=True)

,Unnamed: 0.1,OBJECTID,CUL_CAMPAN,CUL_ID_x,OSA_ID,Shape_Leng,Shape_Area,layer,path,geometry,...,CUL_ID_y,year,auc,gdd,ndvi,doy,percentile,status,pct_diff_from_P80_avg,pct_diff_from_P95_avg
0,0,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,6207146,2020,715.156919,[ 9.30395851 17.41073786 24.87887332 3...,[0.2897824 0.2903328 0.2908832 0.2914336 0.291...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",8.0,non-bearing,-60.213821,-65.239412
1,1,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,6207146,2019,802.833826,[2.76291555e+00 4.08390350e+00 5.42935321e+00 ...,[0.418858 0.419126 0.419662 0.41993 0.421...,"Index([ 32, 33, 35, 36, 37, 38, 39, 40,...",12.0,non-bearing,-55.336110,-60.977828
2,2,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,6207146,2021,828.386356,[ 7.7562856 14.98012911 21.56475207 2...,[0.3588246 0.3588132 0.3588018 0.3587904 0.358...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",14.0,non-bearing,-53.914551,-59.735834
3,3,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,6207146,2018,923.572266,[2.14352633e+00 3.38184980e+00 4.79958865e+00 ...,[0.4980526 0.4981752 0.4982978 0.4984204 0.498...,"Index([ 32, 33, 34, 35, 36, 37, 40, 41,...",22.0,non-bearing,-48.619093,-55.109271
4,4,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,6207146,2022,1105.964848,[ 5.91835175 11.64991811 16.86310527 2...,[0.2914412 0.2924854 0.2935296 0.2945738 0.295...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",42.0,non-bearing,-38.472083,-46.243981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4636,4636,3960341,2024,6433929,48946008,711.316223,27950.570203,Idanha_almonds_2024,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.21549 39.87413, -7.21553 39...",...,6433929,2020,1308.877273,[ 9.30395851 17.41073786 24.87887332 3...,[0.69636461 0.69781386 0.69926311 0.70071236 0...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",65.0,bearing,-27.183498,-36.381313
4637,4637,3960341,2024,6433929,48946008,711.316223,27950.570203,Idanha_almonds_2024,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.21549 39.87413, -7.21553 39...",...,6433929,2019,1316.752251,[2.76291555e+00 4.08390350e+00 5.42935321e+00 ...,[0.7266768 0.72553578 0.72325374 0.72297023 0...,"Index([ 32, 33, 35, 36, 37, 38, 39, 40,...",66.0,bearing,-26.745391,-35.998546
4638,4638,3960341,2024,6433929,48946008,711.316223,27950.570203,Idanha_almonds_2024,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.21549 39.87413, -7.21553 39...",...,6433929,2018,1324.672528,[2.14352633e+00 3.38184980e+00 4.79958865e+00 ...,[0.74448287 0.73728509 0.73008732 0.72288954 0...,"Index([ 32, 33, 34, 35, 36, 37, 40, 41,...",66.0,bearing,-26.304764,-35.613577
4639,4639,3960341,2024,6433929,48946008,711.316223,27950.570203,Idanha_almonds_2024,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.21549 39.87413, -7.21553 39...",...,6433929,2023,1485.442518,[9.83590062e-01 2.58705889e+00 5.51611595e+00 ...,[0.80115084 0.78948681 0.77782278 0.77369963 0...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",75.0,bearing,-17.360680,-27.799264
4640,4640,3960341,2024,6433929,48946008,711.316223,27950.570203,Idanha_almonds_2024,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.21549 39.87413, -7.21553 39...",...,6433929,2024,1833.550564,[ 6.50548452 13.01491979 18.94146741 2...,[0.65595098 0.65335643 0.65076189 0.6520124 0...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",93.0,bearing,2.005544,-10.879285

In [38]:
print(type(df))

<class 'geopandas.geodataframe.GeoDataFrame'>

In [39]:
#only plot the bearing fields
df['Growth variability'] = df['pct_diff_from_P95_avg'].copy
df.head()

,Unnamed: 0.1,OBJECTID,CUL_CAMPAN,CUL_ID_x,OSA_ID,Shape_Leng,Shape_Area,layer,path,geometry,...,year,auc,gdd,ndvi,doy,percentile,status,pct_diff_from_P80_avg,pct_diff_from_P95_avg,Growth variability
0,0,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2020,715.156919,[ 9.30395851 17.41073786 24.87887332 3...,[0.2897824 0.2903328 0.2908832 0.2914336 0.291...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",8.0,non-bearing,-60.213821,-65.239412,<bound method NDFrame.copy of 0 -65.23941...
1,1,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2019,802.833826,[2.76291555e+00 4.08390350e+00 5.42935321e+00 ...,[0.418858 0.419126 0.419662 0.41993 0.421...,"Index([ 32, 33, 35, 36, 37, 38, 39, 40,...",12.0,non-bearing,-55.336110,-60.977828,<bound method NDFrame.copy of 0 -65.23941...
2,2,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2021,828.386356,[ 7.7562856 14.98012911 21.56475207 2...,[0.3588246 0.3588132 0.3588018 0.3587904 0.358...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",14.0,non-bearing,-53.914551,-59.735834,<bound method NDFrame.copy of 0 -65.23941...
3,3,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2018,923.572266,[2.14352633e+00 3.38184980e+00 4.79958865e+00 ...,[0.4980526 0.4981752 0.4982978 0.4984204 0.498...,"Index([ 32, 33, 34, 35, 36, 37, 40, 41,...",22.0,non-bearing,-48.619093,-55.109271,<bound method NDFrame.copy of 0 -65.23941...
4,4,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2022,1105.964848,[ 5.91835175 11.64991811 16.86310527 2...,[0.2914412 0.2924854 0.2935296 0.2945738 0.295...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",42.0,non-bearing,-38.472083,-46.243981,<bound method NDFrame.copy of 0 -65.23941...

In [ ]:
df['Growth variability [%]'] = df['pct_diff_from_P95_avg'].where(df['status']!='non-bearing',np.nan)
df.head()

,Unnamed: 0.1,OBJECTID,CUL_CAMPAN,CUL_ID_x,OSA_ID,Shape_Leng,Shape_Area,layer,path,geometry,...,year,auc,gdd,ndvi,doy,percentile,status,pct_diff_from_P80_avg,pct_diff_from_P95_avg,Growth variability
0,0,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2020,715.156919,[ 9.30395851 17.41073786 24.87887332 3...,[0.2897824 0.2903328 0.2908832 0.2914336 0.291...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",8.0,non-bearing,-60.213821,-65.239412,NaN
1,1,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2019,802.833826,[2.76291555e+00 4.08390350e+00 5.42935321e+00 ...,[0.418858 0.419126 0.419662 0.41993 0.421...,"Index([ 32, 33, 35, 36, 37, 38, 39, 40,...",12.0,non-bearing,-55.336110,-60.977828,NaN
2,2,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2021,828.386356,[ 7.7562856 14.98012911 21.56475207 2...,[0.3588246 0.3588132 0.3588018 0.3587904 0.358...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",14.0,non-bearing,-53.914551,-59.735834,NaN
3,3,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2018,923.572266,[2.14352633e+00 3.38184980e+00 4.79958865e+00 ...,[0.4980526 0.4981752 0.4982978 0.4984204 0.498...,"Index([ 32, 33, 34, 35, 36, 37, 40, 41,...",22.0,non-bearing,-48.619093,-55.109271,NaN
4,4,25737,2024,6207146,9164476,1331.235358,102332.206794,alqueva_almonds_terriak_selection,C:/Users/ici-1/Desktop/NADJA/Verrio/Data/Shape...,"MULTIPOLYGON (((-7.85659 38.0506, -7.85588 38....",...,2022,1105.964848,[ 5.91835175 11.64991811 16.86310527 2...,[0.2914412 0.2924854 0.2935296 0.2945738 0.295...,"Index([ 32, 33, 34, 35, 36, 37, 38, 39,...",42.0,non-bearing,-38.472083,-46.243981,NaN

In [ ]:
@interact(year=widgets.IntSlider(
    min=df['year'].min(), max=df['year'].max(), step=1, value=df['year'].min()))
def show_map(year):
    filtered = df[df['year'] == year].copy()

    # Create display column for tooltip with NaN handling
    filtered["pct_diff_display"] = filtered["Growth variability"].apply(
        lambda x: "non-bearing" if pd.isna(x) else f"{x:.2f}"
    )

    # Ensure GeoDataFrame with CRS
    if not isinstance(filtered, gpd.GeoDataFrame):
        filtered = gpd.GeoDataFrame(filtered, geometry='geometry')
    if filtered.crs is None:
        filtered.set_crs("EPSG:4326", inplace=True)

    # Fix centroid warning using projected CRS
    projected = filtered.to_crs(epsg=3857)
    centroids = projected.geometry.centroid
    lat = centroids.to_crs(epsg=4326).y.max()
    lon = centroids.to_crs(epsg=4326).x.max()

    # Define red → yellow → green ramp
    colormap = cm.LinearColormap(
        colors=["red", "yellow", "green"],
        vmin=df["Growth variability"].min(),
        vmax=df["Growth variability"].max()
    )
    colormap.caption = "Growth variability"

    # Style function for color mapping and NaNs
    def style_function(feature):
        value = feature['properties']['Growth variability']
        if value is None or pd.isna(value):
            return {
                'fillColor': 'none',
                'color': 'black',
                'weight': 1,
                'fillOpacity': 0
            }
        else:
            return {
                'fillColor': colormap(value),
                'color': 'black',
                'weight': 1,
                'fillOpacity': 0.6
            }

    # Tooltip using preprocessed display column
    tooltip = folium.GeoJsonTooltip(
        fields=["pct_diff_display"],
        aliases=["Growth variability"],
        localize=True,
        sticky=True,
        labels=True,
        style=("background-color: white; color: #333; font-family: arial; font-size: 12px; padding: 5px;")
    )

    # Add GeoJson to map
    folium.Map(location=[lat, lon], zoom_start=13, tiles="CartoDB positron")
    m = folium.Map(location=[lat, lon], zoom_start=13, tiles="CartoDB positron")

    folium.GeoJson(
        filtered,
        name="fields",
        style_function=style_function,
        tooltip=tooltip
    ).add_to(m)

    colormap.add_to(m)
    folium.LayerControl().add_to(m)
    display(m)

interactive(children=(IntSlider(value=2018, description='year', max=2024, min=2018), Output()), _dom_classes=(…

In [ ]:
def create_map_for_year(year, save_html=False):
    filtered = df[df['year'] == year].copy()

    # Ensure it's a valid GeoDataFrame with CRS
    if not isinstance(filtered, gpd.GeoDataFrame):
        filtered = gpd.GeoDataFrame(filtered, geometry='geometry')
    if filtered.crs is None:
        filtered.set_crs("EPSG:4326", inplace=True)

    # Calculate centroids
    centroids = filtered.geometry.centroid
    lat = centroids.y.mean()
    lon = centroids.x.mean()

    # Set up colormap
    values = filtered['pct_diff_from_P95_avg']
    colormap = cm.linear.YlOrRd_09.scale(values.min(), values.max())
    colormap.caption = "Pct diff from P95 avg"

    # Create folium map
    m = folium.Map(location=[lat, lon], zoom_start=13, tiles="CartoDB positron")

    folium.GeoJson(
        filtered,
        name="fields",
        style_function=lambda feature: {
            'fillColor': colormap(feature['properties']['pct_diff_from_P95_avg']),
            'color': 'black',
            'weight': 1,
            'fillOpacity': 0.6
        },
        tooltip=folium.GeoJsonTooltip(fields=["pct_diff_from_P95_avg"])
    ).add_to(m)

    colormap.add_to(m)
    folium.LayerControl().add_to(m)

    if save_html:
        m.save(f"map_{year}.html")
        print(f"Saved map to map_{year}.html")

    return m

In [ ]:
for yr in df['year'].unique():
    create_map_for_year(yr, save_html=True)

In [49]:
# Your GeoDataFrame must have these columns
# - 'geometry' (valid geometries)
# - 'year'
# - 'pct_diff_from_P95_avg'

from folium import Element

# Get center of map from entire dataset
centroids = df.geometry.centroid
lat = centroids.y.mean()
lon = centroids.x.mean()

# Create base map
m = folium.Map(location=[lat, lon], zoom_start=13, tiles="CartoDB positron")

# Colormap setup
all_values = df['pct_diff_from_P95_avg']
colormap = cm.linear.YlOrRd_09.scale(all_values.min(), all_values.max())
colormap.caption = "Pct diff from P95 avg"
colormap.add_to(m)

# Dictionary to keep layers by year
year_layers = {}

for year in sorted(df['year'].unique()):
    filtered = df[df['year'] == year]

    layer = folium.FeatureGroup(name=str(year), show=False)

    folium.GeoJson(
        filtered,
        name=f"Fields {year}",
        style_function=lambda feature: {
            'fillColor': colormap(feature['properties']['pct_diff_from_P95_avg']),
            'color': 'black',
            'weight': 1,
            'fillOpacity': 0.6
        },
        tooltip=folium.GeoJsonTooltip(fields=["pct_diff_from_P95_avg"])
    ).add_to(layer)

    layer.add_to(m)
    year_layers[year] = layer

# Activate only the first year
first_year = sorted(year_layers.keys())[0]
year_layers[first_year].show = True

# Layer control
folium.LayerControl(collapsed=False).add_to(m)

# Create the dropdown HTML separately
dropdown_options = ''.join([f'<option value="{year}">{year}</option>' for year in sorted(year_layers.keys())])

dropdown_script = """
<select id="yearDropdown" onchange="switchYear(this.value)"
        style="position: fixed; top: 10px; left: 50px; z-index: 9999;">
  {options}
</select>

<script>
    function switchYear(year) {{
        const yearLayers = {years};
        map.eachLayer(function(layer) {{
            if (layer.options && layer.options.name && yearLayers.includes(layer.options.name)) {{
                if (layer.options.name === year) {{
                    map.addLayer(layer);
                }} else {{
                    map.removeLayer(layer);
                }}
            }}
        }});
    }}
</script>
""".format(
    options=dropdown_options,
    years=str([str(y) for y in year_layers.keys()])  # safely embed year list as JS array
)

# Add to map
m.get_root().html.add_child(Element(dropdown_script))

C:\Users\ici-1\AppData\Local\Temp\ipykernel_15084\4046819578.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  centroids = df.geometry.centroid

In [50]:
# Save the map to HTML
m.save("interactive_map_with_dropdown.html")
print("Map saved to interactive_map_with_dropdown.html")

Map saved to interactive_map_with_dropdown.html